server:
 port: 8082
spring:
 activemq:
  broker-url: tcp://127.0.0.1:61616
  user: admin
  password: admin
 #jms:
  #listener:
   #max-concurrency: 10
 pool:
  enabled: true
  max-connections: 50
  expiry-timeout: 10000
  idle-timeout: 30000
 datasource:
  driver-class-name : com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/local_test_sql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  username : root
  password : 123456
queue: producter1
